### ISSUE TITLE
Accessing environment variables within recipes

### ISSUE THREAD

**Issue by raryanpur** [silitics/rugpi#33]
Are user-defined environment variables accessible within recipes?

For example, given a GitHub Action with the following step,

```
- name: Bake Image (Pi4)
        env:
          MY_ENV_VAR: ${{ vars.MY_ENV_VAR }}
        run: ./run-bakery bake image pi4 build/image-pi4.img
```

Is it possible to access `${MY_ENV_VAR}` in the recipes within a layer build? Have experimented with it a bit and don't think `MY_ENV_VAR` is accessible, but think I'm probably doing something wrong.
